//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 data_scrambler.rc 使用
//
#define IDC_BN_DELETE_TEXT              3
#define IDC_BUTTON_ADD                  3
#define IDC_BUTTON_REPLACE              4
#define IDC_OUTPUT_CONTENT_METHOD_RESET 5
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BROWSER_CONTROL_DIALOG      102
#define IDD_HTML_MAKER_CONFIG_DIALOG    103
#define IDD_CAPTURE_INPUT_DLG           104
#define IDD_HTML_ELEMENT_PROPERTIES_DLG 104
#define IDR_HTML_LOGNOTIFYDHTML_DIALOG  104
#define IDD_HTML_ELEMENT_SCRIPT_DLG     105
#define IDD_BROWSER_CONTROL_DIALOG1     106
#define IDW_WEBBROWSER_WINDOW           106
#define IDD_BROWSER_TEST_DIALOG         109
#define IDD_XPATH_EDIT_DLG              110
#define IDR_POPUP_EDIT                  119
#define IDR_POPUP_INSTANCE_EDIT         120
#define IDR_MAINFRAME                   128
#define IDB_BITMAP_ICONS                129
#define IDI_ICON1                       130
#define IDD_DIALOG_UPDATE               134
#define IDD_DIALOG_OUTPUT_SELECT        135
#define IDD_DIALOG1                     136
#define IDD_DIALOG_OBJECT_PROPERTY      136
#define IDD_DIALOG_LIST_SCRAMBLE        137
#define IDD_DIALOG2                     138
#define IDD_DIALOG_JUMP_INSTRUCTION     138
#define IDD_OVERVIEW                    139
#define IDR_MENU1                       139
#define IDD_SCRAPY_DLG                  139
#define IDR_MENU_EDITOR                 139
#define IDR_HTML_OVERVIEW_DIALOG        140
#define IDD_DIALOG3                     140
#define IDD_DIALOG_TEXT_OUTPUT          140
#define IDD_DIALOG_DATA_STRUCT_DLG      141
#define IDD_DIALOG4                     142
#define IDD_DIALOG_OUTPUT_CONFIG        142
#define IDD_DIALOG_LOCATE_URL           143
#define IDD_DIALOG_SQL_CONN             144
#define IDD_DIALOG_DATA_SET_CONFIG      145
#define IDD_DIALOG_USER_LOGIN           146
#define IDD_DIALOG_WELCOME              147
#define IDR_TXT_WELCOME                 148
#define IDD_DIALOG_DATA_LIST            149
#define IDD_DIALOG_DATAS_LIST           150
#define IDD_DIALOG_USAGE_INTRO          151
#define IDR_TXT_USAGE_INTRO             153
#define IDR_TXT1                        154
#define IDD_DIALOG5                     155
#define IDD_DIALOG_XPATH_COMPARE        155
#define IDD_DIALOG_PLUGIN_MANAGE        156
#define IDD_HTML_PAGE_PROCESS_DLG       157
#define IDD_SCRAPY_DLG1                 158
#define IDD_SCRAPY_EDIT_DLG             158
#define IDD_HTTP_LOG_DLG                158
#define IDD_DIALOG_                     160
#define IDD_DIALOG_SUGEEST              160
#define IDD_DIALOG_HELP                 160
#define IDD_DIALOG_ERROR_PROCESS        161
#define IDB_BITMAP_WX_BARCODE           162
#define IDB_DOWN                        375
#define IDR_EVENTLOG                    396
#define IDB_FILETRANSFER                411
#define IDP_PROCESS                     415
#define IDP_FILE                        416
#define IDP_REGISTRY                    418
#define IDC_LIST_HTML_ELEMENT           1000
#define IDC_URL                         1002
#define IDC_LIST_HTML_PAGE              1004
#define ID_BACK                         1004
#define IDC_BUTTON_ADD_HTML_INFO        1005
#define ID_FORWARD                      1005
#define IDC_EDIT_URL_HTML_ELEMENT       1006
#define ID_STOP                         1006
#define IDC_BUTTON_DELETE_HTML_INFO     1007
#define IDC_STATIC_URL_HTML_ELEMENT     1008
#define ID_HOME                         1008
#define IDC_BUTTON_PICK_UP_HTML_ELEMENTS 1009
#define IDC_STATUS_TEXT                 1009
#define IDC_ANIMATE1                    1010
#define IDC_BUTTON_SAVE                 1011
#define IDC_BUTTON_RECORD_SELECTED      1014
#define IDC_WEB_BROWSER_CONTROL         1015
#define IDC_BUTTON_NEW_PAGE_GROUP       1016
#define IDC_EDIT_TEXT_NAME              1016
#define IDC_BUTTON_RECORD_PAGE          1017
#define IDC_EDIT_TEXT                   1017
#define IDC_STATIC_TEXT                 1018
#define IDC_BUTTON_CPATURE_INPUT        1018
#define IDC_BUTTON_RUN_SCRIPT           1018
#define IDC_STATIC_TEXT_NAME            1019
#define IDC_STATIC_TEXT_NAME2           1020
#define IDC_STATIC_TEXT_BLOCKS          1020
#define IDC_LIST_TEXT_BLOCKS            1021
#define IDC_BN_ADD_TEXT                 1022
#define IDC_STATIC_SCRAMBLE_DUMP        1023
#define IDC_STATIC_TEXT_XPATH           1024
#define IDC_EDIT_TEXT_XPATH             1025
#define IDC_EDIT_XPATH                  1025
#define IDC_EXPLORER2                   1026
#define IDC_EDIT_CONFIG_FILE_NAME       1026
#define IDC_TEST_URL                    1027
#define IDC_EDIT_CONTENT_OUTPUT_PATH    1027
#define IDC_EDIT_SHUTDOWN_SYSTEM_DELAY  1027
#define IDC_EDIT_XPATH1                 1028
#define IDC_EDIT_XPATH2                 1029
#define IDC_EDIT_XPATH_OUTPUT           1030
#define IDC_STATIC_XPATH1               1031
#define IDC_STATIC_XPATH2               1032
#define IDC_STATIC_XPATH_OUTPUT         1033
#define IDC_CHECK_COMBINE               1034
#define IDC_EDIT1                       1035
#define IDC_EDIT_OUTPUT_PATH            1035
#define IDC_EDIT_INPUT_CONTENT          1035
#define IDC_EDIT_XPATH_OUTPUT2          1035
#define IDC_EDIT_LOCATE_URL             1035
#define IDC_EDIT_SQL_SERVER_IP          1035
#define IDC_EDIT_PASSWORD               1035
#define IDC_EDIT_PLUGIN_PATH            1035
#define IDC_COMBO1                      1036
#define IDC_COMBO_OUTPUT_TYPE           1036
#define IDC_COMBO_ACTION                1036
#define IDC_EDIT_SQL_SERVER_PORT        1036
#define IDC_STATIC_OUTPUT_TYPE          1037
#define IDC_COMBO_CONTANT_TYPE          1037
#define IDC_EDIT_SQL_DATA_BASE          1037
#define IDC_STATIC_OUTPUT_PATH          1038
#define IDC_EDIT_SQL_USER_NAME          1038
#define IDC_BUTTON1                     1039
#define IDC_EDIT_SQL_PASSWORD           1039
#define IDC_PROGRESS_WHOLE_UPDATE       1040
#define IDC_BUTTON_CHECK_NEXT_LINK      1040
#define IDC_EDIT_OUTPUT_PATH2           1040
#define IDC_EDIT_SQL_CONN_STRING        1040
#define IDC_STATIC_FILE_UPDATE_TIP      1041
#define IDC_BUTTON_CHECK_CONTENTS       1041
#define IDC_STATIC_OUTPUT_PATH2         1041
#define IDC_PROGRESS_FILE_UPDATE        1042
#define IDC_BN_OUTPUT_CONFIG            1042
#define IDC_BUTTON3                     1042
#define IDC_BUTTON_SQL_CONN_SETTING     1042
#define IDC_STATIC_UPDATE_TIP2          1043
#define IDC_STATIC_UPDATE_TIP           1043
#define IDC_STATIC_DONATE               1043
#define IDC_BN_OUTPUT_CONFIG2           1043
#define IDC_BN_SCRAMBLE_CONFIG          1043
#define IDC_BUTTON2                     1044
#define IDC_BUTTON_DONATE               1044
#define IDC_CHECK_OUTPUT_TO_DATA_CENTER 1045
#define IDC_CHECK_OUTPUT_LINK_LIST      1046
#define IDC_STATIC_WHOLE_UPDATE_TIP     1047
#define IDC_BUTTON_SQL_CONN_CHECK       1047
#define IDC_BUTTON_HELP                 1048
#define IDC_STATIC_DONATE2              1048
#define IDC_STATIC_ACTION               1049
#define IDC_LIST_OBJECTS                1050
#define IDC_BUTTON_WEB_PAGE_LAYOUT      1050
#define IDC_STATIC_OBJECT_PROPERTY      1051
#define IDC_CHECK_OUTPUT_TO_DATA_CENTER2 1051
#define IDC_CHECK_SHARE_SCRIPT_TO_CENTER 1051
#define IDC_STATIC_PROPERTY_TEXT        1052
#define IDC_STATIC_ACTION_PARAMTERS     1056
#define IDC_STATIC_OBJECT_PROPERTY2     1058
#define IDC_BUTTON_XPATH_VALIDATE       1060
#define IDC_STATIC_ACTION_PARAMETER     1061
#define IDC_LIST2                       1062
#define IDC_LIST_ELEMENTS               1062
#define IDC_BUTTON_EXECUTE              1063
#define IDC_BUTTON_                     1064
#define IDC_BUTTON_FILE_BROWSER         1064
#define IDC_STATIC_LIST_LINK            1064
#define IDC_BUTTON_COPY                 1064
#define IDC_STATIC_LINK_LIST_DESC       1065
#define IDC_BUTTON_LOAD                 1065
#define IDC_BUTTON_OPEN                 1065
#define IDC_STATIC_NEXT_LIST            1066
#define IDC_BUTTON_FILE_BROWSER2        1066
#define IDC_BUTTON_OUTPUT_CONTENT_BROWSER 1066
#define IDC_BUTTON_PLUGINS              1066
#define IDC_BUTTON_XPATH_EDIT           1067
#define IDC_BUTTON_OUTPUT_METHOD_CONFIRM 1068
#define IDC_STATIC_CONTENTS             1069
#define IDC_BUTTON_EXIT_SYSTEM          1069
#define IDC_BUTTON_CHECK_LIST_LINKS     1070
#define IDC_BUTTON_EXIT_SYSTEM2         1070
#define IDC_BUTTON_CANCEL_EXIT_SYSTEM   1070
#define IDC_LIST_CONTENT_ELEMENTS       1071
#define IDC_BUTTON_CHECK_LIST_LINKS2    1072
#define IDC_BUTTON_RECORD_LINKS         1072
#define IDC_BUTTON_LIST_LINK_OK         1073
#define IDC_BUTTON_NEXT_LINK_OK         1074
#define IDC_STATIC_NEXT_LINK_DESC       1075
#define IDC_STATIC_CONTENTS_DESC        1076
#define IDC_STATIC_ELEMENT_COUNT        1077
#define IDC_BUTTON_CONTENTS_RETURN      1078
#define IDC_BUTTON_NEXT_LINK_RETURN     1079
#define IDC_RICHEDIT21                  1080
#define IDC_RICHEDIT21_CONTENT          1080
#define IDC_RICHEDIT_OUTPUT             1080
#define IDC_RICHEDIT21_TEXT             1080
#define IDC_RICHEDIT21_XPATH_COMPARE    1080
#define IDC_RICHEDIT21_SCRIPT           1080
#define IDC_STATIC_ELEMENT_COUNT2       1081
#define IDC_STATIC_ELEMENT_URL          1081
#define IDC_SPIN1                       1081
#define IDC_LIST_DATAS                  1082
#define IDC_STATIC_HELP_DESC            1083
#define IDC_BUTTON_XOR_XPATH            1084
#define IDC_TREE                        1085
#define IDC_TREE_ELEMENTS               1085
#define IDC_BUTTON_XOR_XPATH2           1085
#define IDC_BUTTON_HILIGHT              1085
#define IDC_STATIC_TIP                  1086
#define IDC_CHECK1                      1087
#define IDC_CHECK_LOAD_WEB_PAGE         1087
#define IDC_CHECK_MYSQL                 1087
#define IDC_STATIC_CONFIG_FILE_PATH     1088
#define IDC_RICHEDIT22                  1089
#define IDC_RICHEDIT2_PROPERTY_TEXT     1089
#define IDC_RICHEDIT2_EDIT_SCRIPT       1089
#define IDC_RICHEDIT2_SCRIPT            1089
#define IDC_STATIC_SCRIPT_MANAGE        1090
#define IDC_STATIC_SCRAMBLE_MANAGE      1091
#define IDC_COMBO_OUTPUT_METHOD         1092
#define IDC_RICHEDIT_SCRAPY             1092
#define IDC_LIST1                       1093
#define IDC_LIST3                       1094
#define IDC_LIST_HTML_DATA_SETS         1094
#define IDC_STATIC_FIELD_DESC           1095
#define IDC_EDIT2                       1096
#define IDC_EDIT_OUTPUT_FIELD_NAME      1096
#define IDC_EDIT_USER_NAME              1096
#define IDC_STATIC_OUTPUT_FIELD_NAME    1097
#define IDC_BUTTON_OUTPUT_CONFIG        1098
#define IDC_SLIDER1                     1099
#define IDC_SLIDER_WEB_PAGE_LOAD_TIME   1099
#define IDC_SLIDER2                     1100
#define IDC_SLIDER_PROCESS_DELAY_TIME   1100
#define IDC_STATIC_WEG_PAGE_LOAD_TIME   1101
#define IDC_STATIC_PROCESS_DELAY_TIME   1102
#define IDC_BUTTON_SAVE_HTML_SCRIPT     1103
#define IDC_BUTTON_DATA_PROCESS         1104
#define IDC_BUTTON_DATA_PROCESS2        1105
#define IDC_BUTTON_DATA_LEARNING        1105
#define IDC_STATIC_DELAY_SHUTDOWN_TIME  1106
#define IDC_LIST_HTML_ITEMS             1107
#define IDC_LIST_HTML_PAGES2            1108
#define IDC_LIST_HTML_PAGES             1108
#define IDC_LIST_HTML_DATA_SET          1108
#define IDC_STATIC_LOCATE_URL           1109
#define IDC_LIST_HTML_LOCATE_URL        1109
#define IDC_LIST_DATA_SET               1110
#define IDC_STATIC_SQL_SERVER_IP        1111
#define IDC_STATIC_SQL_SERVER_PORT      1112
#define IDC_STATIC_SQL_DATA_BASE        1113
#define IDC_STATIC_SQL_USER_NAME        1114
#define IDC_STATIC_SQL_PASSWORD         1115
#define IDC_STATIC_USER_NAME            1116
#define IDC_STATIC_PASSWORD             1117
#define IDC_STATIC_DATA_OUTPUT_STATUS   1118
#define IDC_STATIC_USER_REGISTER        1119
#define IDC_BUTTON_GET_ACCESS           1121
#define IDC_STATIC_USAGE_INTRO          1122
#define IDC_STATIC_XPATH_ANALYZE_DESC   1123
#define IDC_BUTTON_BROWSER              1124
#define IDC_STATIC_PLUGIN_PATH          1125
#define IDC_BUTTON_BROWSER2             1126
#define IDC_BUTTON_ADD_PLUGIN           1126
#define IDC_BUTTON_BROWSER3             1127
#define IDC_BUTTON_ADD_PLUGIN2          1128
#define IDC_BUTTON_DEL_PLUGIN           1128
#define IDC_LIST_PLUGINS                1129
#define IDC__MODE_TAB                   1130
#define IDC_MODE_TAB                    1130
#define IDC_CUSTOM1                     1131
#define IDC_RICHEDIT2_LOG               1132
#define IDC_STATIC_HELP                 1133
#define IDC_STATIC_QQ_GROUP             1134
#define IDC_STATIC_QQ                   1135
#define IDC_STATIC_WEIXIN               1136
#define IDC_STATIC_BUY_LINK2            1136
#define IDC_STATIC_WEIXIN_CODE          1137
#define IDC_STATIC_QQ_GROUP2            1137
#define IDC_PICTURE_WX_BARCODE          1138
#define IDC_STATIC_BUY_LINK1            1139
#define IDC_RICHEDIT_TEXT               1139
#define IDC_STATIC_                     1140
#define IDC_STATIC_SAVE_FILE_STATE      1140
#define IDC_STATIC_BUY_LINK3            1140
#define IDC_STATIC_DONAT                1140
#define IDC_BUTTON_XPATH_CLEAN          1141
#define IDP_BROWSE                      2002
#define ID_EDIT_JUMP                    32771
#define ID_EDIT_DELETE                  32772
#define ID_EDIT_EDIT                    32773
#define ID_MENU_ITEM_EDIT               32774
#define ID_MENU_ITEM_DELETE             32775
#define ID_MENU_ITEM_JUMP               32776
#define ID_32777                        32777
#define ID_MENU_ITEM_LINKS              32778
#define ID_32779                        32779
#define ID_MENU_ITEM_RUN                32780
#define ID_32781                        32781
#define ID_32782                        32782
#define ID_32783                        32783
#define ID_MENU_ITEM_CUT                32784
#define ID_MENU_ITEM_COPY               32785
#define ID_MENU_ITEM_PASTE              32786
#define ID_MENU_ITEM_UPDATE_URL         32787
#define ID_32788                        32788
#define ID_MENU_ITEM_RESET              32789
#define ID_FILE_32790                   32790
#define ID_MENU_PASTE                   32791
#define ID_MENU_ITEM_CLEAR              32792
#define ID_32793                        32793
#define ID_MENU_ITEM_HILIGHT            32794

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1141
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
